// Generated by nitro

// App Config
import type { Defu } from 'defu'



type UserAppConfig = Defu<{}, []>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}
  interface NitroRuntimeConfig {
   public: {
      device: {
         enabled: boolean,

         defaultUserAgent: string,

         refreshOnResize: boolean,
      },
   },
  }
}
export {}